### ISSUE TITLE
Unknown Public Key [Arch linux AUR]

### ISSUE THREAD

**Issue by marcusva** [marcusva/py-sdl2#102]
Originally reported by: **Alex Anderson (Bitbucket: [appins](https://bitbucket.org/appins), GitHub: [appins](https://github.com/appins))**

----------------------------------------

The Arch Linux's AUR does not allow me to install this package because of failed PGP signatures.

----------------------------------------
- Bitbucket: https://bitbucket.org/marcusva/py-sdl2/issue/102

**Comment by paolobb4** [comment]
From the AUR package python-pysdl2's page ([link](https://aur.archlinux.org/packages/python-pysdl2/)):
> In order to make the GPG verification work, you have to import the key of Marcus von Appen:
> 
> gpg --recv-keys --keyserver hkp://pgp.mit.edu F5645D06D1395E36

Word of advice: When installing from AUR, always check the comments in the package's page for preventable problems, especialy the *Pinned Comments* since those were highlighted by the package's mantainer ;)


I'd consider this issue closed.
