### ISSUE TITLE
Texture sprite center always None

### ISSUE THREAD

**Issue by mtn** [marcusva/py-sdl2#105]
It seems to me that TextureSprites have an issue that becomes exposed only when we try to print one of them out (which instantly fails). Center is initialized to `None` in the contructor, and as far as I can tell, the center setter is never used. There's also another minor issue that the return value of `__retr__` refers to `self.center` instead of `self._center`.

I don't know enough about the internals of SDL to know if something is going on here that I'm missing. I'm pretty sure as is, this represents a bug since center either 1) shouldn't *have* to be set, and things should work if it isn't or 2) it should have to be set with some mechanism that forces you to do so. Apologies in advance if I'm speaking nonsense!

**Comment by marcusva** [comment]
`TextureSprite`'s constructor is used in the `SpriteFactory` code. The center is set to `None` on purpose, since a set value would `SDL_RenderCopyEx` to behave differently in the `TextureSpriteRenderSystem`. The constructor however does not allow kwargs at the moment, thus an `exec()` on `__repr__()` would not recreate the sprite.

You are however right: the center should not be printed, if it is unset. `__repr__` refers to `self.center` to allow the center to be overridden properly without having to fear a misbehaviour in subclasses, so I'd like to keep that unchanged. Do you mind to update your pull request? I'll gladly incorporate it then.

**Comment by mtn** [comment]
Gotcha, thanks for the reply. To confirm, we should check if `self._center` is set and if it is, return with `self.center` (and otherwise ignore it), right?

**Comment by marcusva** [comment]
A simple check for self.center should be enough:

```
if self.center != None:
  return "TextureSprite... , (self.center.x, self.center.y))
else:
  return "TextureSprite...
```

**Comment by mtn** [comment]
There's always a lot to unwrap with graphics programming and I haven't used SDL much even without the wrapper, so I can't say I fully understand what goes on with `SDL_RenderCopyEx`, but thanks for the help and I'm glad we resolved this :)
