### ISSUE TITLE
SDL_RWclose() doesn't seem to like whatever comes out of SDL_RWFromMem()

### ISSUE THREAD

**Issue by etc0de** [marcusva/py-sdl2#130]
According to the SDL 2 wiki, [SDL_RWFromMem](https://wiki.libsdl.org/SDL_RWFromMem) returns `SDL_RWops*`, and [SDL_RWclose](https://wiki.libsdl.org/SDL_RWclose) takes `SDL_RWops*`. Based on that, I tried the following code:
```
#!/usr/bin/python3

import ctypes
import sdl2

sdl2.SDL_Init(sdl2.SDL_INIT_EVERYTHING)

# Make an SDL_RWops object and destroy it again:
array = bytearray(b"this is a funny test!")
ctypes_bytes = (ctypes.c_uint8 * len(array)).from_buffer(array)
rwops = sdl2.SDL_RWFromMem(ctypes.byref(ctypes_bytes), len(ctypes_bytes))
sdl2.SDL_RWclose(rwops)
```
But it fails:
```
$ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 12, in <module>
    sdl2.SDL_RWclose(rwops)
  File "/usr/local/lib/python3.6/site-packages/sdl2/rwops.py", line 66, in <lambda>
    SDL_RWclose = lambda ctx: ctx.close(ctx)
AttributeError: 'LP_SDL_RWops' object has no attribute 'close'
```
Is this a bug or did I just completely misunderstand something? :confused:

**Comment by JonasT** [comment]
Ok, it seems `sdl2.SDL_RWclose(rwops.contents)` works. However, that seems like a bug to me, because the original call in C would be `SDL_RWops* rwops; ... SDL_RWclose(rwops);` rather than `SDL_RWclose(*rwops);` or anything along the lines.

Maybe the wrapper function could be changed to accept both if that other variant is needed for anything?

**Comment by a-hurst** [comment]
Hi @etc0de, thanks for taking the time to file an issue report! *Technically* it's not a bug: At present, `SDL_RWclose` and a few of the other `SDL_RW` functions are rewritten in Python, and as a consequence expect a `SDL_RWops` object as input instead of a pointer to one (which `sdl2.SDL_RWFromMem` and similar functions return). To access the actual object and fix your example code, all you need is to use `rwops.contents` instead of `rwops`. If I change your example accordingly, it works fine for me:

```python
import ctypes
import sdl2

sdl2.SDL_Init(sdl2.SDL_INIT_EVERYTHING)

# Make an SDL_RWops object and destroy it again:
array = bytearray(b"this is a funny test!")
ctypes_bytes = (ctypes.c_uint8 * len(array)).from_buffer(array)
rwops = sdl2.SDL_RWFromMem(ctypes.byref(ctypes_bytes), len(ctypes_bytes))
sdl2.SDL_RWclose(rwops.contents)
```

**However**, having looked at this now, I'd agree this is confusing and unexpected behaviour from an end-user perspective (especially since the SDL2 docs say `SDL_RWclose` and family takes a `SDL_RWops` pointer as an argument). To fix this, I've modified the pysdl2 code so `SDL_RWclose`, `SDL_RWsize`, `SDL_RWwrite`, etc. will automatically use a pointer's `.contents` if a pointer is passed to one, meaning that both our examples should work without issue. Thanks again!
