### ISSUE TITLE
SDL_GetPrefPath should return a c_char_p

### ISSUE THREAD

**Issue by benob** [marcusva/py-sdl2#135]
It currently returns a LP_c_char but it should really return a c_char_p.
Then, the user then has to free it as per the documentation.

**Comment by a-hurst** [comment]
Hopefully fixed in the latest commit, thanks for the report! Also, since ctypes is just returning a byte string it's no longer possible to call SDL_free on it (since SDL_free expects a pointer to the character array), but I'd imagine ctypes handles that for us anyway since it's converting the returned array to a string for us.
