### ISSUE TITLE
SDL_SysWMmsg structure is undefined, even though the definition seems to already have been written

### ISSUE THREAD

**Issue by Rojetto** [marcusva/py-sdl2#136]
I wanted to read `SDL_SysWMEvent`s to get notified of DPI changes on Windows 10, but the returned structure `SDL_SysWMmsg` in the `msg` field is undefined in PySDL2:

    # TODO
    class SDL_SysWMmsg(Structure):
        pass

There oddly seems to be a complete definition in syswm.py that is not used. Is there a specific reason for this, or is it just an oversight?

EDIT: I found a workaround by casting to a pointer to the structure that is defined in syswm.py

    message_pointer = sdl2_event.syswm.msg
    # Workaround because the default pointer type that is returned has no definition for the structure
    message_pointer_usable = ctypes.cast(message_pointer, ctypes.POINTER(sdl2.syswm.SDL_SysWMmsg))
    sys_wm_msg = message_pointer_usable.contents

**Comment by a-hurst** [comment]
Hi @Rojetto, thanks for reporting this! I've updated pysdl2 so that the events module imports the complete definition from syswm. Since I'm on macOS (no support in SDL2 for window events yet) and it's not easy to test window operations with CI, would you be able to test out the latest commit on your end and let me know if it works as expected now?

**Comment by Rojetto** [comment]
Thanks for the fix. Seems like it works, in my quick test the window event data now had the correct structure and I could read the parameters.

**Comment by a-hurst** [comment]
Great, thanks so much for checking.
