### ISSUE TITLE
examples gui.py  get error in macbook pro 

### ISSUE THREAD

**Issue by mahaidong** [marcusva/py-sdl2#149]
`$ python gui.py`

```
Using software rendering
Traceback (most recent call last):
  File "gui.py", line 155, in <module>
    sys.exit(run())
  File "gui.py", line 130, in run
    spriterenderer = factory.create_sprite_render_system(window)
  File "/usr/local/miniconda3/envs/pythonocc/lib/python3.7/site-packages/sdl2/ext/sprite.py", line 482, in create_sprite_render_system
    return SoftwareSpriteRenderSystem(*args, **kwargs)
  File "/usr/local/miniconda3/envs/pythonocc/lib/python3.7/site-packages/sdl2/ext/sprite.py", line 683, in __init__
    raise SDLError()
sdl2.ext.common.SDLError: b'No hardware accelerated renderers available'
```

**Comment by mahaidong** [comment]
how can i force software rendering?

**Comment by a-hurst** [comment]
Huh, I get the same error on macOS with gui.py. I'll take a look and get back to you.

**Comment by a-hurst** [comment]
Ah, so what's happening here is that `gui.py` defaults to expecting a software renderer unless otherwise specified but doesn't *force* a software renderer, and macOS defaults to a hardware renderer unless you specifically tell it not to. After making it force a software renderer unless the `-hardware` flag is given it works properly, albeit with some odd graphical glitches on my end:

![Screen Shot 2019-12-15 at 10 59 17 AM](https://user-images.githubusercontent.com/18648066/70865377-ecca7480-1f2a-11ea-94bb-422e5592ae89.png)

With the `-hardware` flag there aren't any weird artifacts.

**Comment by mahaidong** [comment]
@a-hurst  thanks
