### ISSUE TITLE
event.key.keysym.sym is wrong for sdl.SDL_KEYDOWN/sdl.SDL_KEYUP events on ARM64/postmarketOS/sdl2-2.0.12-r1

### ISSUE THREAD

**Issue by ell1e** [marcusva/py-sdl2#167]
The value of event.key.keysym.sym is wrong for sdl.SDL_KEYDOWN/sdl.SDL_KEYUP events on ARM64/postmarketOS/sdl2-2.0.12-r1. For example, this is what I get for a `t` key: 1073742095, when it should be `116` according to SDL_keycode.h.

This is on an ARM64 device running postmarketOS (based on Alpine Linux) with sdl2-2.0.12-r1. It works fine on my Fedora 32 x64 machine with its SDL2 2.0.12-1.fc32, so I do wonder if this is a bug with PySDL2's assumption of how the event struct is laid out on ARM64 platforms? At least that is my best guess as to what the issue could be.

Edit: also yes, that means all key input other than SDL_TEXTINPUT is currently unusable on that platform which is a bit of a shame :cry:

**Comment by a-hurst** [comment]
This is a really weird bug, thanks for bringing it to our attention! Unfortunately I don’t have any ARM hardware capable of running a proper Linux distro so I can’t reproduce and debug that way, but I’m pretty sure Travis CI offers ARM instances now so I can give that a shot and see if I can reproduce it that way.

Unless I’m mistaken, the SDL2 structs are written so they’re consistent across architectures and platforms, so I’m guessing this is Python’s ctypes library acting wonky.

**Comment by a-hurst** [comment]
@ell1e I added an ARM64 instance to our CI testing suite and the full testing suite passed without issue. Unfortunately, it's not testing keypress events because I'm not sure how to test that on a headless CI instance, but it at least rules out a major endianness/arm64 bug with Python ctypes and SDL2.

Can I confirm what version of Python you're using? The CI instance is testing with 3.8, so maybe it's fixed a bug present in earlier versions. Also, have you tried out any other SDL2-based games or test programs on your postmarketOS devices? Just wondering if the bug could be at the SDL2 binary level for your OS/architecture and not at the Python or py-sdl2 level.

**Comment by ell1e** [comment]
Ok, it does seem to be a bug with the on-screen keyboard in combination with SDL2 actually, how wild: https://source.puri.sm/Librem5/squeekboard/-/issues/218

So this isn't caused by PySDL2, sorry for not checking earlier. I guess it makes sense to close this then
