### ISSUE TITLE
Question: How portable is this?

### ISSUE THREAD

**Issue by MakerMatrix** [marcusva/py-sdl2#179]
I'm thinking of using py-sdl2 for a project but before committing to that have a general question about portability across multiple embedded platforms.  How should we think about that?  What are the underpinnings required for this to work, and how often do you find SBCs/microprocessors for which said underpinnings are not up to snuff, to support for example the sdl_image stuff?  I really just need to draw images at around 1fps, and/or kivy widgets.  I think the demands are not too crazy but I'm new to all this.

**Comment by a-hurst** [comment]
Hey @MakerMatrix, sounds like a cool project! The portability of py-sdl2 really comes down to how exotic your hardware is: basically, if your hardware and OS is supported by SDL2 and can also run Python, it *should* be able to run py-sdl2 without issue.

SDL2 itself is extremely portable, running on everything from the Nintendo Switch to Haiku OS to the Raspberry Pi. It even has a maintained OS/2 Warp port last I checked! If your SBC hardware runs Linux and supports any form of OpenGL or KMS/DRM rendering you should have no issues whatsoever.

As for the SDL2 sub-packages (image, TTF, mixer, gfx), I have our CI set up to install all of those and test them with py-sdl2 on an ARM64 Linux instance and it's been passing without trouble so far.

**Comment by MakerMatrix** [comment]
Thanks for the answer.  It is leading to more questions. ;-)

On embedded platforms, does OpenGL (ES?) sit on top of SDL, or is it the other way around?  I'm trying to understand how the software layers are built up, starting from the frame buffer (which I guess is the lowest level thing with a standard interface?).

In principle the hardware could get exotic, because one of the goals of the project is to be able to drive extremely high resolution displays (hoping to get 8k on one physical screen) which is why I'm wondering about this.  Surely in the beginning it won't be too exotic.  Pi3/4, Beaglebone green/black, PINE64 boards are the things I've got on hand for developement/testing right now.

**Comment by a-hurst** [comment]
@MakerMatrix You can use SDL2's surface/renderer API for putting stuff on screen (which would use OpenGL or OpenGL ES as a back-end), or you can use OpenGL directly with SDL2 by simply providing a window for the GL context: it's entirely up to you! There's an example illustrating how to do the latter in PySDL2 in the repository (via PyOpenGL), and it's also what I personally use for my main PySDL2-based project. This setup is nice because PyOpenGL uses Numpy arrays for texture input, which can be generated easily from images or shapes using Python packages like Pillow or Aggdraw.

Not sure about the Beaglebone or the Pi, but FYI the Pine A64 has a proper & fully open-source community driver for the GPU that supports full desktop OpenGL (with some minimal restrictions) in addition to the usual OpenGL ES. So does its big brother, the RockPro64. Being able to get inside the GPU driver code might be handy for driving a display at those sorts of speeds!
