### ISSUE TITLE
Is There A Discord Server Dedicated To PySDL2?

### ISSUE THREAD

**Issue by mandaw2014** [marcusva/py-sdl2#194]
Is There A Discord Server Dedicated to PySDL2?

If there isn't, it would very cool and helpful to have one.

**Comment by a-hurst** [comment]
Hey @mandaw2014, there's no official one yet! I agree that it would be nice to have, especially with the documentation and examples being somewhat out-of-date, but I'd have no idea about the time and effort required to set one up.

If there's any sort of unofficial one (or a general Python game development discord server with a PySDL2 channel) I'll add a link in the README and come hang out there, but otherwise I can't really spare the time to set up and moderate that sort of thing. I'm currently around on the PursuedPyBear Discord server though (an educational game engine built on PySDL2), so you can sometimes find me on there!

**Comment by a-hurst** [comment]
@mandaw2014 I've officially partnered up with the PursuedPyBear project for shared infrastructure stuff, and they've been kind enough to provide a me a Discord channel on their server dedicated to PySDL2: https://discord.com/channels/521542709798764544/931292746478657576

Drop by if you want to chat!
