### ISSUE TITLE
gfxdrawing example presents context in the wrong place (?)

### ISSUE THREAD

**Issue by marcusva** [marcusva/py-sdl2#22]
Originally reported by: **Brett Calcott (Bitbucket: [bcalcott](https://bitbucket.org/bcalcott), GitHub: Unknown)**

----------------------------------------

The gfxdrawing example calls context.present() every pass through the loop. This cause flashing on OSX. I changed it calls it only calls it when the drawing changes:

```
#!diff

diff --git a/examples/gfxdrawing.py b/examples/gfxdrawing.py
--- a/examples/gfxdrawing.py
+++ b/examples/gfxdrawing.py
@@ -304,6 +304,7 @@
     # which function to execute next.
     curindex = 0
     draw_lines(context, 800, 600)
+    context.present()
 
     # The event loop is nearly the same as we used in colorpalettes.py. If you
     # do not know, what happens here, take a look at colorpalettes.py for a
@@ -325,8 +326,8 @@
                 # function with the arguments.
                 func, args = functions[curindex]
                 func(*args)
+                context.present()
                 break
-        context.present()
     sdl2ext.quit()
     return 0
 

```

----------------------------------------
- Bitbucket: https://bitbucket.org/marcusva/py-sdl2/issue/22

**Comment by a-hurst** [comment]
I've sort of fixed this in the latest commit, by tweaking the demo to behave the same as the `gui.py` demo does: that is, default to software rendering (which doesn't have the issue) but allow hardware rendering by passing the `-hardware` flag to the script. I also enabled vsync for hardware rendering, which seemed to improve (but not fix) the issue on my Mac.

During my searches I found a lot of people talking about flicker issues using SDL2 Renderers with the OpenGL back-end, most of which were using SDL2 with C directly, so I'm going to assume this is a low-level SDL2 problem rather than a py-sdl2 problem. Oddly enough, the example renders perfectly fine with the OpenGL backend in a Mojave VM on my desktop, so it might have to do with differences in the quality of macOS OpenGL drivers for different graphics cards. Also, only certain SDL2_gfx drawing functions seem to set it off: for example, I don't get any flicker when drawing a scene using only `sdlgfx.lineColor()`, but if I add `sdlgfx.thickLineColor()` or `sdlgfx.aalineColor()` the flicker problem appears.

Anyway, since this doesn't seem to be py-sdl2's fault and the new defaults for the example eliminate the issue, I think it's fair to close this.
